version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spring-demo
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  ecommerce-api:
    container_name: ecommerce_api
    # Remplacer build par image
    image: ${DOCKER_HUB_USERNAME}/ecommerce_api:${IMAGE_TAG}
    ports:
      - "8087:8087"
    networks:
      - spring-demo
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/ecommerce

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql_data:
    driver: local